# .goreleaser.yml
project_name: gourdiantoken
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yourusername/gourdiantoken.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./gourdiantoken.go

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: yourusername
    name: gourdiantoken
  draft: false
  prerelease: true