# .goreleaser.yml
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/gourdian25/gourdiantoken.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: gourdian25
    name: gourdiantoken
  draft: false
  prerelease: true