// File: gourdiantoken.repository.postgres.imp.go

package gourdiantoken

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/gourdian25/gourdiantoken/v2/internal/postgresdb"
)

// postgresSchemaSQL is internal/postgresdb/schema.sql, embedded so
// PostgresTokenRepository can apply it on connect without a separate
// migration tool — this package has one linear schema, and
// CREATE TABLE IF NOT EXISTS is sufficient. The query code itself is
// generated by sqlc from the same directory (see internal/postgresdb) into
// its own internal package, isolating generated code from hand-written code.
//
//go:embed internal/postgresdb/schema.sql
var postgresSchemaSQL string

// gourdiantokenSchemaLockKey is a fixed Postgres advisory-lock key used by
// applyPostgresSchema to serialize schema application across concurrent
// callers — e.g. multiple service replicas racing on first boot against a
// fresh database, where concurrent CREATE TABLE/INDEX IF NOT EXISTS
// statements are not fully race-free in Postgres. Advisory locks are global
// to the database, not namespaced per application, so an unrelated app that
// happens to choose this same int64 key could in principle collide with it
// — an accepted, extremely unlikely risk, not worth a namespacing scheme for
// a single fixed lock. Distinct from grnoti's own lock key
// (7_927_100_419), since the two libraries may share a database.
const gourdiantokenSchemaLockKey int64 = 8_314_672_205

// PostgresTokenRepository implements TokenRepository using pgx/v5 and
// sqlc-generated queries against PostgreSQL.
//
// Unlike the removed GORM-based repository, this implementation never dials
// its own connection: the caller always constructs and owns the
// *pgxpool.Pool (see NewPostgresTokenRepository), so it can be shared with
// the rest of your backend instead of each store opening its own pool.
// Close() closes the pool that was passed in, matching this package's
// existing Redis/Mongo repository convention (see NewRedisTokenRepository,
// NewMongoTokenRepository) — if you need to keep using the pool after the
// repository is closed, do not call Close() on the repository; close the
// pool yourself when your application shuts down instead.
//
// Database Schema:
//   - gourdiantoken_revoked_tokens: token_hash + token_type composite unique
//     key, indexed on token_type and expires_at
//   - gourdiantoken_rotated_tokens: token_hash unique key, indexed on
//     expires_at
//
// Security Considerations:
//   - Only token hashes are stored, never the actual tokens
//   - Composite unique index prevents duplicate revocations
//   - Automatic expiration via TTL-based cleanup
type PostgresTokenRepository struct {
	pool      *pgxpool.Pool
	q         *postgresdb.Queries
	closeOnce sync.Once
}

// NewPostgresTokenRepository creates a new pgx-based token repository backed
// by an existing connection pool.
//
// Initialization Steps:
//  1. Ping the pool to validate connectivity
//  2. Apply the embedded schema (CREATE TABLE/INDEX IF NOT EXISTS),
//     serialized by a Postgres advisory lock so concurrent callers building
//     a repository against the same fresh database don't race on the DDL
//  3. Return the initialized repository instance
//
// Parameters:
//   - ctx: Context for the connectivity check and schema application
//   - pool: An already-constructed *pgxpool.Pool. Never nil. The caller
//     retains ownership — build it once and share it across your backend;
//     see docs/postgres.md for the recommended shared-pool pattern.
//
// Returns:
//   - TokenRepository: Initialized Postgres repository instance
//   - error: If pool is nil, the connectivity check fails, or schema
//     application fails
//
// Example:
//
//	pool, err := pgxpool.New(ctx, dsn)
//	if err != nil {
//	    log.Fatal(err)
//	}
//	defer pool.Close()
//
//	repo, err := gourdiantoken.NewPostgresTokenRepository(ctx, pool)
//	if err != nil {
//	    log.Fatalf("failed to create token repository: %v", err)
//	}
func NewPostgresTokenRepository(ctx context.Context, pool *pgxpool.Pool) (TokenRepository, error) {
	if pool == nil {
		return nil, fmt.Errorf("pgx pool cannot be nil")
	}

	pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		return nil, fmt.Errorf("database connection failed: %w", err)
	}

	if err := applyPostgresSchema(ctx, pool); err != nil {
		return nil, fmt.Errorf("failed to apply schema: %w", err)
	}

	return &PostgresTokenRepository{
		pool: pool,
		q:    postgresdb.New(pool),
	}, nil
}

// applyPostgresSchema applies the embedded schema against pool, serialized
// by a Postgres session-level advisory lock (gourdiantokenSchemaLockKey) so
// concurrent callers apply it one at a time instead of racing on catalog
// DDL. The lock/exec/unlock sequence runs on a single acquired connection,
// since advisory locks are session-scoped, and is unlocked explicitly
// before the connection is released back to the pool — a released pooled
// connection is reused, not reset, so the lock would otherwise leak onto
// whichever caller acquires that connection next.
func applyPostgresSchema(ctx context.Context, pool *pgxpool.Pool) error {
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire connection: %w", err)
	}
	defer conn.Release()

	if _, err := conn.Exec(ctx, "SELECT pg_advisory_lock($1)", gourdiantokenSchemaLockKey); err != nil {
		return fmt.Errorf("acquire schema lock: %w", err)
	}
	defer func() {
		_, _ = conn.Exec(ctx, "SELECT pg_advisory_unlock($1)", gourdiantokenSchemaLockKey)
	}()

	if _, err := conn.Exec(ctx, postgresSchemaSQL); err != nil {
		return err
	}
	return nil
}

// pgTimestamptz converts a time.Time to the pgtype every generated query
// param expects.
func pgTimestamptz(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: !t.IsZero()}
}

// MarkTokenRevoke marks a token as revoked by storing its hash.
// Uses an atomic UPSERT to handle concurrent revocation attempts.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - tokenType: Type of token (AccessToken, RefreshToken, or VerificationToken)
//   - token: The actual token string to revoke
//   - ttl: Time-to-live duration for the revocation record
//
// Returns:
//   - error: If token is empty, TTL is invalid, token type is invalid,
//     or the database operation fails
func (r *PostgresTokenRepository) MarkTokenRevoke(ctx context.Context, tokenType TokenType, token string, ttl time.Duration) error {
	if token == "" {
		return fmt.Errorf("token cannot be empty")
	}
	if ttl <= 0 {
		return fmt.Errorf("ttl must be positive")
	}
	if tokenType != AccessToken && tokenType != RefreshToken && tokenType != VerificationToken {
		return fmt.Errorf("invalid token type: %s", tokenType)
	}

	now := time.Now()
	err := r.q.UpsertRevokedToken(ctx, postgresdb.UpsertRevokedTokenParams{
		TokenHash: hashToken(token),
		TokenType: string(tokenType),
		ExpiresAt: pgTimestamptz(now.Add(ttl)),
		CreatedAt: pgTimestamptz(now),
	})
	if err != nil {
		return fmt.Errorf("failed to mark token as revoked: %w", err)
	}
	return nil
}

// IsTokenRevoked checks if a token has been revoked by checking its hash.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - tokenType: Type of token to check
//   - token: The token string to check for revocation
//
// Returns:
//   - bool: True if token is revoked and not expired, false otherwise
//   - error: If token is empty, token type is invalid, or the database
//     operation fails
func (r *PostgresTokenRepository) IsTokenRevoked(ctx context.Context, tokenType TokenType, token string) (bool, error) {
	if token == "" {
		return false, fmt.Errorf("token cannot be empty")
	}
	if tokenType != AccessToken && tokenType != RefreshToken && tokenType != VerificationToken {
		return false, fmt.Errorf("invalid token type: %s", tokenType)
	}

	count, err := r.q.CountRevokedToken(ctx, postgresdb.CountRevokedTokenParams{
		TokenHash: hashToken(token),
		TokenType: string(tokenType),
		ExpiresAt: pgTimestamptz(time.Now()),
	})
	if err != nil {
		return false, fmt.Errorf("database error: %w", err)
	}
	return count > 0, nil
}

// MarkTokenRotated marks a token as rotated by storing its hash.
// Uses an atomic UPSERT for idempotent rotation tracking.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - token: The refresh token being rotated
//   - ttl: Time-to-live duration for the rotation record
//
// Returns:
//   - error: If token is empty, TTL is invalid, or the database operation fails
func (r *PostgresTokenRepository) MarkTokenRotated(ctx context.Context, token string, ttl time.Duration) error {
	if token == "" {
		return fmt.Errorf("token cannot be empty")
	}
	if ttl <= 0 {
		return fmt.Errorf("ttl must be positive")
	}

	now := time.Now()
	err := r.q.UpsertRotatedToken(ctx, postgresdb.UpsertRotatedTokenParams{
		TokenHash: hashToken(token),
		ExpiresAt: pgTimestamptz(now.Add(ttl)),
		CreatedAt: pgTimestamptz(now),
	})
	if err != nil {
		return fmt.Errorf("failed to mark token as rotated: %w", err)
	}
	return nil
}

// MarkTokenRotatedAtomic marks a token as rotated atomically, returning
// whether it was newly rotated. Uses INSERT ... ON CONFLICT DO NOTHING so
// only the first caller for a given token hash sees rotated=true — essential
// for preventing double-spending in rotation flows.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - token: The refresh token being rotated
//   - ttl: Time-to-live duration for the rotation record
//
// Returns:
//   - bool: True if the token was newly rotated, false if already rotated
//   - error: If token is empty, TTL is invalid, or the database operation fails
func (r *PostgresTokenRepository) MarkTokenRotatedAtomic(ctx context.Context, token string, ttl time.Duration) (bool, error) {
	if token == "" {
		return false, fmt.Errorf("token cannot be empty")
	}
	if ttl <= 0 {
		return false, fmt.Errorf("ttl must be positive")
	}

	now := time.Now()
	rowsAffected, err := r.q.InsertRotatedTokenIfNotExists(ctx, postgresdb.InsertRotatedTokenIfNotExistsParams{
		TokenHash: hashToken(token),
		ExpiresAt: pgTimestamptz(now.Add(ttl)),
		CreatedAt: pgTimestamptz(now),
	})
	if err != nil {
		return false, fmt.Errorf("failed to mark token as rotated: %w", err)
	}
	return rowsAffected > 0, nil
}

// IsTokenRotated checks if a token has been rotated by checking its hash.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - token: The token to check for rotation status
//
// Returns:
//   - bool: True if token has been rotated and not expired, false otherwise
//   - error: If token is empty or the database operation fails
func (r *PostgresTokenRepository) IsTokenRotated(ctx context.Context, token string) (bool, error) {
	if token == "" {
		return false, fmt.Errorf("token cannot be empty")
	}

	count, err := r.q.CountRotatedToken(ctx, postgresdb.CountRotatedTokenParams{
		TokenHash: hashToken(token),
		ExpiresAt: pgTimestamptz(time.Now()),
	})
	if err != nil {
		return false, fmt.Errorf("database error: %w", err)
	}
	return count > 0, nil
}

// GetRotationTTL returns the remaining TTL for a rotated token.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - token: The token to check for remaining TTL
//
// Returns:
//   - time.Duration: Remaining TTL if the token is rotated and not expired, 0 otherwise
//   - error: If token is empty or the database operation fails
func (r *PostgresTokenRepository) GetRotationTTL(ctx context.Context, token string) (time.Duration, error) {
	if token == "" {
		return 0, fmt.Errorf("token cannot be empty")
	}

	expiresAt, err := r.q.GetRotatedTokenExpiresAt(ctx, hashToken(token))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("database error: %w", err)
	}

	remaining := time.Until(expiresAt.Time)
	if remaining < 0 {
		return 0, nil
	}
	return remaining, nil
}

// CleanupExpiredRevokedTokens removes expired revoked tokens from the database.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//   - tokenType: Type of tokens to clean up
//
// Returns:
//   - error: If token type is invalid or the database operation fails
func (r *PostgresTokenRepository) CleanupExpiredRevokedTokens(ctx context.Context, tokenType TokenType) error {
	if tokenType != AccessToken && tokenType != RefreshToken && tokenType != VerificationToken {
		return fmt.Errorf("invalid token type: %s", tokenType)
	}

	_, err := r.q.DeleteExpiredRevokedTokens(ctx, postgresdb.DeleteExpiredRevokedTokensParams{
		TokenType: string(tokenType),
		ExpiresAt: pgTimestamptz(time.Now()),
	})
	if err != nil {
		return fmt.Errorf("failed to cleanup expired revoked tokens: %w", err)
	}
	return nil
}

// CleanupExpiredRotatedTokens removes expired rotated tokens from the database.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//
// Returns:
//   - error: If the database operation fails
func (r *PostgresTokenRepository) CleanupExpiredRotatedTokens(ctx context.Context) error {
	_, err := r.q.DeleteExpiredRotatedTokens(ctx, pgTimestamptz(time.Now()))
	if err != nil {
		return fmt.Errorf("failed to cleanup expired rotated tokens: %w", err)
	}
	return nil
}

// Stats returns statistics about the repository for monitoring and debugging.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//
// Returns:
//   - map[string]interface{}: Dictionary of statistics metrics
//   - error: If any count operation fails
func (r *PostgresTokenRepository) Stats(ctx context.Context) (map[string]interface{}, error) {
	totalRevoked, err := r.q.CountAllRevokedTokens(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to count revoked tokens: %w", err)
	}

	accessCount, err := r.q.CountRevokedTokensByType(ctx, string(AccessToken))
	if err != nil {
		return nil, fmt.Errorf("failed to count access tokens: %w", err)
	}

	refreshCount, err := r.q.CountRevokedTokensByType(ctx, string(RefreshToken))
	if err != nil {
		return nil, fmt.Errorf("failed to count refresh tokens: %w", err)
	}

	verificationCount, err := r.q.CountRevokedTokensByType(ctx, string(VerificationToken))
	if err != nil {
		return nil, fmt.Errorf("failed to count verification tokens: %w", err)
	}

	rotatedCount, err := r.q.CountRotatedTokens(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to count rotated tokens: %w", err)
	}

	return map[string]interface{}{
		"total_revoked_tokens":        totalRevoked,
		"revoked_access_tokens":       accessCount,
		"revoked_refresh_tokens":      refreshCount,
		"revoked_verification_tokens": verificationCount,
		"rotated_tokens":              rotatedCount,
	}, nil
}

// CleanupAll removes all expired tokens (both revoked and rotated) in one operation.
//
// Parameters:
//   - ctx: Context for cancellation and timeout
//
// Returns:
//   - error: If any cleanup operation fails, with detailed context
func (r *PostgresTokenRepository) CleanupAll(ctx context.Context) error {
	if err := r.CleanupExpiredRevokedTokens(ctx, AccessToken); err != nil {
		return fmt.Errorf("failed to cleanup access tokens: %w", err)
	}
	if err := r.CleanupExpiredRevokedTokens(ctx, RefreshToken); err != nil {
		return fmt.Errorf("failed to cleanup refresh tokens: %w", err)
	}
	if err := r.CleanupExpiredRevokedTokens(ctx, VerificationToken); err != nil {
		return fmt.Errorf("failed to cleanup verification tokens: %w", err)
	}
	if err := r.CleanupExpiredRotatedTokens(ctx); err != nil {
		return fmt.Errorf("failed to cleanup rotated tokens: %w", err)
	}
	return nil
}

// Close closes the underlying connection pool. Idempotent: safe to call
// multiple times.
//
// Important: this closes the *pgxpool.Pool passed to
// NewPostgresTokenRepository, matching this package's existing Redis/Mongo
// repository convention. If you share that pool with other stores or the
// rest of your backend, do not call this until everything else sharing it
// has also finished — or don't call it at all, and close the pool yourself
// during application shutdown instead.
//
// Returns:
//   - error: Always nil; present to satisfy the same shape as this
//     package's other repository Close methods.
func (r *PostgresTokenRepository) Close() error {
	r.closeOnce.Do(func() {
		r.pool.Close()
	})
	return nil
}
