// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllRevokedTokens(ctx context.Context) (int64, error)
	CountRevokedToken(ctx context.Context, arg CountRevokedTokenParams) (int64, error)
	CountRevokedTokensByType(ctx context.Context, tokenType string) (int64, error)
	CountRotatedToken(ctx context.Context, arg CountRotatedTokenParams) (int64, error)
	CountRotatedTokens(ctx context.Context) (int64, error)
	CountTenantRevocations(ctx context.Context) (int64, error)
	DeleteExpiredRevokedTokens(ctx context.Context, arg DeleteExpiredRevokedTokensParams) (int64, error)
	DeleteExpiredRotatedTokens(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteExpiredTenantRevocations(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	GetRotatedTokenExpiresAt(ctx context.Context, tokenHash string) (pgtype.Timestamptz, error)
	GetTenantRevocationEpoch(ctx context.Context, arg GetTenantRevocationEpochParams) (pgtype.Timestamptz, error)
	// Conditional upsert rather than a plain ON CONFLICT DO NOTHING: a conflicting row whose
	// expires_at has already passed is stale (its previous rotation TTL fully elapsed without
	// cleanup running yet) and should be treated as a fresh rotation, not a live conflict. The
	// WHERE clause makes Postgres report 0 affected rows exactly when the existing row is still
	// live (expires_at > EXCLUDED.created_at, i.e. "now"), which is the same "conflict, do
	// nothing" outcome as before for that case — the Go-side `rowsAffected > 0` check needs no
	// change.
	InsertRotatedTokenIfNotExists(ctx context.Context, arg InsertRotatedTokenIfNotExistsParams) (int64, error)
	// File: internal/postgresdb/queries/tokens.sql
	UpsertRevokedToken(ctx context.Context, arg UpsertRevokedTokenParams) error
	UpsertRotatedToken(ctx context.Context, arg UpsertRotatedTokenParams) error
	UpsertTenantRevocation(ctx context.Context, arg UpsertTenantRevocationParams) error
}

var _ Querier = (*Queries)(nil)
